version: "3.9"

services:
  express:
    container_name: ${SERVICE_NAME}
    image: ${SERVICE_NAME}
    working_dir: ${WORKING_DIRECTORY}
    volumes:
      - .:${WORKING_DIRECTORY}
    restart: always
    ports:
      - "4000:${LISTENING_PORT}"
    command: npm run start
    env_file:
      - .env
    networks:
      - docker_express_network
  db:
    container_name: docker_mysql
    image: mysql:8.1.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - docker_express_network

volumes:
  db_data:
    name: docker_mysql_db_data

networks:
  docker_express_network:
    name: docker_express_network
    driver: bridge